name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Set node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm run lint

  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Set node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install
        run: pnpm install --frozen-lockfile
        working-directory: packages/nimiq-vts

      - name: Lint
        run: pnpm -w run lint
        working-directory: packages/nimiq-vts

      - name: Typecheck
        run: pnpm -w run typecheck
        working-directory: packages/nimiq-vts

      - name: Test
        run: pnpm -w run test
        working-directory: packages/nimiq-vts
