name: Sync Mainnet

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *' # Runs every hour

jobs:
  mainnet:
    needs: []
    uses: ./.github/workflows/sync.yml
    with:
      network: mainnet
      api_url: 'https://validators-api-mainnet.nuxt.dev'
